/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import SystemsController.SystemFacede;
import entity.Admin;
import entity.Besin;
import entity.Besinkategori;
import java.util.List;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class adminForm extends javax.swing.JFrame {
    
    private SystemFacede systemFacede;
    
    private DefaultTableModel model;
    
    private adminBilgiGuncelle adminBilgiGuncelleForm;
    
    public adminForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table_admin = new javax.swing.JTable();
        btn_bilgileri_guncelle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_besin = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_guncelle = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_ekle = new javax.swing.JButton();
        txt_isim = new javax.swing.JTextField();
        txt_protein = new javax.swing.JTextField();
        txt_kalori = new javax.swing.JTextField();
        txt_yag = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_karbonhidrat = new javax.swing.JTextField();
        comboBox_kategori = new javax.swing.JComboBox<>();
        btn_cikis = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kategori_isim = new javax.swing.JTextField();
        btn_kategoriEkle = new javax.swing.JButton();
        btn_kategori_sil = new javax.swing.JButton();
        btn_kategori_guncelle = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_kategori = new javax.swing.JTable();
        btn_duyuru = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_admin.setBackground(new java.awt.Color(126, 24, 126));
        table_admin.setForeground(new java.awt.Color(255, 255, 255));
        table_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ADMİN", "YAŞ", "CİNSİYET", "EMAIL", "KAYIT TARİHİ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_admin.setGridColor(new java.awt.Color(255, 255, 255));
        table_admin.setRowHeight(50);
        table_admin.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(table_admin);
        if (table_admin.getColumnModel().getColumnCount() > 0) {
            table_admin.getColumnModel().getColumn(0).setResizable(false);
            table_admin.getColumnModel().getColumn(1).setResizable(false);
            table_admin.getColumnModel().getColumn(2).setResizable(false);
            table_admin.getColumnModel().getColumn(3).setResizable(false);
            table_admin.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_bilgileri_guncelle.setText("BİLGİLERİ GÜNCELLE");
        btn_bilgileri_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bilgileri_guncelleActionPerformed(evt);
            }
        });

        table_besin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "İSİM", "KALORİ", "KARBONHİDRAT", "PROTEİN", "YAG", "KATEGORİ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_besin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_besinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_besin);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("İsim:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Kalori:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Karbonhidrat:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Kategori:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Yağ:");

        btn_guncelle.setText("GÜNCELLE");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_sil.setText("SİL");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_ekle.setText("EKLE");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        txt_protein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_proteinActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Protein:");

        txt_karbonhidrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_karbonhidratActionPerformed(evt);
            }
        });

        btn_cikis.setText("Çıkış Yap");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("KATEGORİ EKLE;");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("BESİN EKLE;");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("İsim:");

        btn_kategoriEkle.setText("EKLE");
        btn_kategoriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kategoriEkleActionPerformed(evt);
            }
        });

        btn_kategori_sil.setText("SİL");
        btn_kategori_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kategori_silActionPerformed(evt);
            }
        });

        btn_kategori_guncelle.setText("GÜNCELLE");
        btn_kategori_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kategori_guncelleActionPerformed(evt);
            }
        });

        table_kategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kategori"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_kategoriMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_kategori);
        if (table_kategori.getColumnModel().getColumnCount() > 0) {
            table_kategori.getColumnModel().getColumn(0).setResizable(false);
            table_kategori.getColumnModel().getColumn(1).setResizable(false);
        }

        btn_duyuru.setText("DUYURU YAYINLA");
        btn_duyuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_duyuruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_kategori_isim, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_bilgileri_guncelle)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_karbonhidrat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kalori, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_protein, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_yag, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_kategoriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_kategori_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_kategori_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(160, 160, 160))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_isim, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(btn_duyuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(927, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_bilgileri_guncelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_duyuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_isim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_kategori_isim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kalori, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_karbonhidrat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_kategoriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kategori_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kategori_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_protein, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_yag, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_kategori))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(646, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bilgileri_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bilgileri_guncelleActionPerformed
        this.getAdminBilgiGuncelleForm().setAform(this);
        this.getAdminBilgiGuncelleForm().setVisible(true);
        this.getAdminBilgiGuncelleForm().getSystemFacede().getAdminSystem().setAdmin(this.getSystemFacede().getAdminSystem().getAdmin());
        this.getAdminBilgiGuncelleForm().bilgileriGetir(this.getSystemFacede().getAdminSystem().getAdmin());

    }//GEN-LAST:event_btn_bilgileri_guncelleActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        this.model = (DefaultTableModel) table_besin.getModel();
        
        this.getSystemFacede().getBesinSystem().getBesin().setBesin_id(Integer.parseInt(model.getValueAt(table_besin.getSelectedRow(), 0).toString()));
        this.getSystemFacede().getBesinSystem().getBesin().setIsim(txt_isim.getText());
        this.getSystemFacede().getBesinSystem().getBesin().setKalori(Double.parseDouble(txt_kalori.getText()));
        this.getSystemFacede().getBesinSystem().getBesin().setKarbonhidrat(Double.parseDouble(txt_karbonhidrat.getText()));
        this.getSystemFacede().getBesinSystem().getBesin().setProtein(Double.parseDouble(txt_protein.getText()));
        this.getSystemFacede().getBesinSystem().getBesin().setYag(Double.parseDouble(txt_yag.getText()));
        this.getSystemFacede().getBesinSystem().getBesin().setBesinkategori(this.getSystemFacede().getBesinkategoriSystem().getBkdao().find(comboBox_kategori.getSelectedItem().toString()));
        
        this.getSystemFacede().getBesinSystem().update();
        
        this.yemekGoster("");
        this.alanlarıSıfırla();

    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        
        this.getSystemFacede().getBesinSystem().getBesin().setIsim(txt_isim.getText());
        this.getSystemFacede().getBesinSystem().getBesin().setKalori(Double.parseDouble(txt_kalori.getText()));
        this.getSystemFacede().getBesinSystem().getBesin().setKarbonhidrat(Double.parseDouble(txt_karbonhidrat.getText()));
        this.getSystemFacede().getBesinSystem().getBesin().setProtein(Double.parseDouble(txt_protein.getText()));
        this.getSystemFacede().getBesinSystem().getBesin().setYag(Double.parseDouble(txt_yag.getText()));
        this.getSystemFacede().getBesinSystem().getBesin().setBesinkategori(this.getSystemFacede().getBesinkategoriSystem().getBkdao().find(comboBox_kategori.getSelectedItem().toString()));
        
        this.getSystemFacede().getBesinSystem().create();
        
        this.yemekGoster("");
        this.alanlarıSıfırla();
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void table_besinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_besinMouseClicked
        this.model = (DefaultTableModel) table_besin.getModel();
        
        txt_isim.setText(model.getValueAt(table_besin.getSelectedRow(), 1).toString());
        txt_kalori.setText(model.getValueAt(table_besin.getSelectedRow(), 2).toString());
        txt_karbonhidrat.setText(model.getValueAt(table_besin.getSelectedRow(), 3).toString());
        txt_protein.setText(model.getValueAt(table_besin.getSelectedRow(), 4).toString());
        txt_yag.setText(model.getValueAt(table_besin.getSelectedRow(), 5).toString());
        

    }//GEN-LAST:event_table_besinMouseClicked

    private void txt_proteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_proteinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_proteinActionPerformed

    private void txt_karbonhidratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_karbonhidratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_karbonhidratActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        this.model = (DefaultTableModel) table_besin.getModel();
        
        this.getSystemFacede().getBesinSystem().getBesin().setBesin_id(Integer.parseInt(model.getValueAt(table_besin.getSelectedRow(), 0).toString()));
        this.getSystemFacede().getBesinSystem().delete();
        
        this.yemekGoster("");
        this.alanlarıSıfırla();

    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        this.setVisible(false);
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void btn_kategoriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kategoriEkleActionPerformed
        this.getSystemFacede().getBesinkategoriSystem().getBk().setBesinkategori_isim(txt_kategori_isim.getText());
        this.getSystemFacede().getBesinkategoriSystem().create();
        this.ComboBoxkategoriGoster();
        this.kategoriGoster();
        this.alanlarıSıfırla();
    }//GEN-LAST:event_btn_kategoriEkleActionPerformed

    private void btn_kategori_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kategori_silActionPerformed
        this.model = (DefaultTableModel) table_kategori.getModel();
        
        this.getSystemFacede().getBesinkategoriSystem().getBk().setBesinkategori_id(Integer.parseInt(model.getValueAt(table_kategori.getSelectedRow(), 0).toString()));
        this.getSystemFacede().getBesinkategoriSystem().delete();
        this.kategoriGoster();
        this.ComboBoxkategoriGoster();
        this.alanlarıSıfırla();
    }//GEN-LAST:event_btn_kategori_silActionPerformed

    private void btn_kategori_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kategori_guncelleActionPerformed
        this.model = (DefaultTableModel) table_kategori.getModel();
        
        this.getSystemFacede().getBesinkategoriSystem().getBk().setBesinkategori_id(Integer.parseInt(model.getValueAt(table_kategori.getSelectedRow(), 0).toString()));
        this.getSystemFacede().getBesinkategoriSystem().getBk().setBesinkategori_isim(txt_kategori_isim.getText());
        
        this.getSystemFacede().getBesinkategoriSystem().update();
        this.kategoriGoster();
        this.ComboBoxkategoriGoster();
        this.yemekGoster("");
    }//GEN-LAST:event_btn_kategori_guncelleActionPerformed

    private void table_kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_kategoriMouseClicked
        this.model = (DefaultTableModel) table_kategori.getModel();
        txt_kategori_isim.setText(model.getValueAt(table_kategori.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_table_kategoriMouseClicked

    private void btn_duyuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_duyuruActionPerformed
        duyuruForm duyuruform = new duyuruForm();
        duyuruform.setVisible(true);
    }//GEN-LAST:event_btn_duyuruActionPerformed
    
    public void admin_goster(Admin admin) {
        this.setModel((DefaultTableModel) table_admin.getModel());
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        Object[] row = new Object[11];
        row[0] = admin.getAd_soyad();
        row[1] = admin.getYas();
        row[2] = admin.getCinsiyet();
        row[3] = admin.getEmail();
        row[4] = admin.getKayit_tarihi();
        model.addRow(row);
    }
    
    public void ComboBoxkategoriGoster() {
        String[] kategoriler = new String[this.getSystemFacede().getBesinkategoriSystem().getBklist().size()];
        for (int i = 0; i < kategoriler.length; i++) {
            kategoriler[i] = this.getSystemFacede().getBesinkategoriSystem().getBklist().get(i).getBesinkategori_isim();
        }
        ComboBoxModel modelcombo = new DefaultComboBoxModel(kategoriler);
        comboBox_kategori.setModel(modelcombo);
    }
    
    public void yemekGoster(String deger) {
        List<Besin> bl = this.getSystemFacede().getBesinSystem().getBdao().ara(deger);
        this.model = (DefaultTableModel) table_besin.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        Object[] row = new Object[7];
        for (int i = 0; i < bl.size(); i++) {
            row[0] = bl.get(i).getBesin_id();
            row[1] = bl.get(i).getIsim();
            row[2] = bl.get(i).getKalori();
            row[3] = bl.get(i).getKarbonhidrat();
            row[4] = bl.get(i).getProtein();
            row[5] = bl.get(i).getYag();
            row[6] = bl.get(i).getBesinkategori().getBesinkategori_isim();
            model.addRow(row);
        }
    }
    
    public void kategoriGoster() {
        List<Besinkategori> bklist = this.getSystemFacede().getBesinkategoriSystem().getBklist();
        this.model = (DefaultTableModel) table_kategori.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        Object[] row = new Object[2];
        for (int i = 0; i < bklist.size(); i++) {
            row[0] = bklist.get(i).getBesinkategori_id();
            row[1] = bklist.get(i).getBesinkategori_isim();
            model.addRow(row);
        }
    }
    
    public void alanlarıSıfırla() {
        txt_isim.setText("");
        txt_karbonhidrat.setText("");
        txt_protein.setText("");
        txt_yag.setText("");
        txt_kalori.setText("");
        comboBox_kategori.setSelectedItem(null);
        txt_kategori_isim.setText("");
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminForm().setVisible(true);
            }
        });
    }
    
    public SystemFacede getSystemFacede() {
        if (this.systemFacede == null) {
            this.systemFacede = new SystemFacede();
        }
        return systemFacede;
    }
    
    public void setSystemFacede(SystemFacede systemFacede) {
        this.systemFacede = systemFacede;
    }
    
    public DefaultTableModel getModel() {
        if (this.model == null) {
            this.model = new DefaultTableModel();
        }
        return model;
    }
    
    public void setModel(DefaultTableModel model) {
        this.model = model;
    }
    
    public adminBilgiGuncelle getAdminBilgiGuncelleForm() {
        if (this.adminBilgiGuncelleForm == null) {
            this.adminBilgiGuncelleForm = new adminBilgiGuncelle();
        }
        return adminBilgiGuncelleForm;
    }
    
    public void setAdminBilgiGuncelleForm(adminBilgiGuncelle adminBilgiGuncelleForm) {
        this.adminBilgiGuncelleForm = adminBilgiGuncelleForm;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bilgileri_guncelle;
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_duyuru;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_kategoriEkle;
    private javax.swing.JButton btn_kategori_guncelle;
    private javax.swing.JButton btn_kategori_sil;
    private javax.swing.JButton btn_sil;
    private javax.swing.JComboBox<String> comboBox_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_admin;
    private javax.swing.JTable table_besin;
    private javax.swing.JTable table_kategori;
    private javax.swing.JTextField txt_isim;
    private javax.swing.JTextField txt_kalori;
    private javax.swing.JTextField txt_karbonhidrat;
    private javax.swing.JTextField txt_kategori_isim;
    private javax.swing.JTextField txt_protein;
    private javax.swing.JTextField txt_yag;
    // End of variables declaration//GEN-END:variables
}
