/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import SystemsController.SystemFacede;

import entity.Kullanici;

import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame {

    private SystemFacede systemFacede;
    private Kullanici girisYapan;
    //private Musteri m = new Musteri();
    // private Admin girisAdmin;

    private musteriForm mform;
    private adminForm aform;

    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        btn_giris = new java.awt.Button();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        txt_login_name = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_kayit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        label1.setFont(new java.awt.Font("AR BONNIE", 1, 48)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 0, 51));
        label1.setName("label_logo"); // NOI18N
        label1.setText("Fit Target");

        btn_giris.setActionCommand("btn_giris");
        btn_giris.setBackground(new java.awt.Color(102, 102, 102));
        btn_giris.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_giris.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btn_giris.setForeground(new java.awt.Color(255, 51, 0));
        btn_giris.setLabel("Giriş");
        btn_giris.setName("btn_giris"); // NOI18N
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });

        label2.setText("Kullanıcı Adı:");

        label3.setText("Şifre:");

        btn_kayit.setText("Kayıt Ol!");
        btn_kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_giris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_login_name)
                            .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btn_kayit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_login_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btn_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_kayit)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed

        if (txt_login_name.getText().equalsIgnoreCase("") || txt_password.getText().equalsIgnoreCase("")) {

            JOptionPane.showMessageDialog(this, "Kullanıcı adı veya şifre alanı boş bırakılamaz!");

        } else {

            girisYapan = this.getSystemFacede().getKullaniciSystem().Login(txt_login_name.getText(), txt_password.getText()); //get password char[]

            if (girisYapan != null) {

                if (this.getSystemFacede().getMusteriSystem().MusteriMi(girisYapan)) {

                    this.getSystemFacede().getMusteriSystem().setM(this.getSystemFacede().getMusteriSystem().getMdao().find(girisYapan));
                    this.getMform().musteri_goster(this.getSystemFacede().getMusteriSystem().getM());
                    this.getMform().yemekGoster("");
                    this.getMform().getSystemFacede().getMusteriSystem().setM(this.getSystemFacede().getMusteriSystem().getM());
                    this.getMform().tuketilenbesinGoster();

                    this.setVisible(false);
                    this.getMform().setVisible(true);

                    if (this.getMform().getNlist().size() > 0) {

                        for (int i = 0; i < this.getMform().getNlist().size(); i++) {
                            if (!this.getMform().Observe(i).equalsIgnoreCase("")) {
                                JOptionPane.showMessageDialog(this.getMform(), this.getMform().Observe(i));
                            }
                        }
                    }
                } else if (this.getSystemFacede().getAdminSystem().AdminMi(girisYapan)) {
                    this.getSystemFacede().getAdminSystem().setAdmin(this.getSystemFacede().getAdminSystem().getAdao().find(girisYapan));
                    this.getAform().admin_goster(this.getSystemFacede().getAdminSystem().getAdmin());
                    this.getAform().yemekGoster("");
                    this.getAform().ComboBoxkategoriGoster();
                    this.getAform().kategoriGoster();
                    this.getAform().getSystemFacede().getAdminSystem().setAdmin(this.getSystemFacede().getAdminSystem().getAdmin());
                    this.setVisible(false);

                    this.getAform().setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Hatalı giriş!");
            }
        }
    }//GEN-LAST:event_btn_girisActionPerformed

    private void btn_kayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitActionPerformed
        kayitForm k = new kayitForm();
        k.setVisible(true);
    }//GEN-LAST:event_btn_kayitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //DENEMEE

        //DENEMEE
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });

    }

    public SystemFacede getSystemFacede() {
        if (this.systemFacede == null) {
            this.systemFacede = new SystemFacede();
        }
        return systemFacede;
    }

    public adminForm getAform() {
        if (this.aform == null) {
            this.aform = new adminForm();
        }
        return aform;
    }

    public Kullanici getGirisYapan() {
        return girisYapan;
    }

    public void setGirisYapan(Kullanici girisYapan) {
        this.girisYapan = girisYapan;
    }

    public musteriForm getMform() {
        if (this.mform == null) {
            this.mform = new musteriForm();
        }
        return mform;
    }

    public void setMform(musteriForm mform) {
        this.mform = mform;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_giris;
    private javax.swing.JButton btn_kayit;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField txt_login_name;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables

}
