/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Observer.NoticeObservable;
import SystemsController.BesinSystem;
import SystemsController.BesinkategoriSystem;
import SystemsController.MusteriSystem;
import SystemsController.SystemFacede;
import entity.Besin;
import entity.Musteri;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class musteriForm extends javax.swing.JFrame {

    private SystemFacede systemFacede;
    NoticeObservable noticeObservable = new NoticeObservable();

    private List<NoticeObservable> nlist = new ArrayList();

    private DefaultTableModel model;

    LoginForm lform = new LoginForm();
    private musteriBilgiGuncelle bform;
    int i = 0;

    public musteriForm() {
        initComponents();

    }

    public String Observe(int i) {
        this.setNlist(this.getSystemFacede().getNoticeObservableSystem().getNoticeList());
        this.getSystemFacede().getMusteriSystem().getM().setObservable(this.nlist.get(i));
        return this.nlist.get(i).notifyObserver(this.getSystemFacede().getMusteriSystem().getM().getKullanici_id());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_bilgileri_guncelle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_musteri = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_kalori = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_tuketilenKarbonhidrat = new javax.swing.JTextField();
        txt_tuketilenKalori = new javax.swing.JTextField();
        txt_tuketilenProtein = new javax.swing.JTextField();
        txt_tuketilenYag = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_kalanKarbonhidrat = new javax.swing.JTextField();
        txt_kalanKalori = new javax.swing.JTextField();
        txt_kalanProtein = new javax.swing.JTextField();
        txt_kalanYag = new javax.swing.JTextField();
        label_kalori1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_yemekAra = new javax.swing.JTextField();
        btn_besin_ekle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_besin = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_tuketilenbesinler = new javax.swing.JTable();
        btn_cikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_bilgileri_guncelle.setText("BİLGİLERİ GÜNCELLE");
        btn_bilgileri_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bilgileri_guncelleActionPerformed(evt);
            }
        });

        table_musteri.setBackground(new java.awt.Color(126, 24, 126));
        table_musteri.setForeground(new java.awt.Color(255, 255, 255));
        table_musteri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÜŞTERİ", "CİNSİYET", "YAŞ", "BOY", "KİLO", "YAĞ ORANI", "HEDEF", "KALORİ HEDEFİ", "KARBONHİDRAT HEDEFİ", "PROTEİN HEDEFİ", "YAĞ HEDEFİ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_musteri.setGridColor(new java.awt.Color(255, 255, 255));
        table_musteri.setRowHeight(50);
        table_musteri.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(table_musteri);
        if (table_musteri.getColumnModel().getColumnCount() > 0) {
            table_musteri.getColumnModel().getColumn(0).setResizable(false);
            table_musteri.getColumnModel().getColumn(1).setResizable(false);
            table_musteri.getColumnModel().getColumn(2).setResizable(false);
            table_musteri.getColumnModel().getColumn(3).setResizable(false);
            table_musteri.getColumnModel().getColumn(4).setResizable(false);
            table_musteri.getColumnModel().getColumn(5).setResizable(false);
            table_musteri.getColumnModel().getColumn(6).setResizable(false);
            table_musteri.getColumnModel().getColumn(7).setResizable(false);
            table_musteri.getColumnModel().getColumn(8).setResizable(false);
            table_musteri.getColumnModel().getColumn(9).setResizable(false);
            table_musteri.getColumnModel().getColumn(10).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setText("HEDEFE KALAN;");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel3.setText("TÜKETİLEN;");

        label_kalori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_kalori.setText("Kalori:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Protein:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Karbonhidrat:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Yağ:");

        txt_tuketilenKarbonhidrat.setEditable(false);
        txt_tuketilenKarbonhidrat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_tuketilenKalori.setEditable(false);
        txt_tuketilenKalori.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_tuketilenProtein.setEditable(false);
        txt_tuketilenProtein.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_tuketilenYag.setEditable(false);
        txt_tuketilenYag.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Protein:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Karbonhidrat:");

        txt_kalanKarbonhidrat.setEditable(false);
        txt_kalanKarbonhidrat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_kalanKalori.setEditable(false);
        txt_kalanKalori.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_kalanProtein.setEditable(false);
        txt_kalanProtein.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_kalanYag.setEditable(false);
        txt_kalanYag.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        label_kalori1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_kalori1.setText("Kalori:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("YEMEK ARA :");

        txt_yemekAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yemekAraActionPerformed(evt);
            }
        });
        txt_yemekAra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_yemekAraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_yemekAraKeyReleased(evt);
            }
        });

        btn_besin_ekle.setText("EKLE");
        btn_besin_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_besin_ekleActionPerformed(evt);
            }
        });

        table_besin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "İSİM", "KALORİ", "KARBONHİDRAT", "PROTEİN", "YAG", "KATEGORİ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_besin);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Yağ:");

        table_tuketilenbesinler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İsim"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(table_tuketilenbesinler);
        if (table_tuketilenbesinler.getColumnModel().getColumnCount() > 0) {
            table_tuketilenbesinler.getColumnModel().getColumn(0).setResizable(false);
        }

        btn_cikis.setText("Çıkış Yap");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_yemekAra, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btn_besin_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_kalori, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tuketilenYag, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tuketilenKarbonhidrat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tuketilenKalori, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tuketilenProtein, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(label_kalori1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(71, 71, 71)
                                    .addComponent(txt_kalanKalori, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_kalanProtein, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_kalanKarbonhidrat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_kalanYag, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_bilgileri_guncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_kalori1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tuketilenKalori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kalanKalori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_kalori, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kalanKarbonhidrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tuketilenKarbonhidrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_kalanProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tuketilenProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tuketilenYag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kalanYag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_yemekAra, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_besin_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_bilgileri_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bilgileri_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bilgileri_guncelleActionPerformed
        this.getBform().setMfrom(this);
        this.getBform().setVisible(true);
        this.getBform().getSystemFacede().getMusteriSystem().setM(this.getSystemFacede().getMusteriSystem().getM());
        this.getBform().bilgileriGetir(this.getSystemFacede().getMusteriSystem().getM());


    }//GEN-LAST:event_btn_bilgileri_guncelleActionPerformed

    private void txt_yemekAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yemekAraActionPerformed

    }//GEN-LAST:event_txt_yemekAraActionPerformed

    private void btn_besin_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_besin_ekleActionPerformed

        this.model = (DefaultTableModel) table_besin.getModel();
        Besin b = new Besin();
        b.setBesin_id(Integer.parseInt(model.getValueAt(table_besin.getSelectedRow(), 0).toString()));
        b.setIsim(model.getValueAt(table_besin.getSelectedRow(), 1).toString());
        b.setKalori(Double.parseDouble(model.getValueAt(table_besin.getSelectedRow(), 2).toString()));
        b.setKarbonhidrat(Double.parseDouble(model.getValueAt(table_besin.getSelectedRow(), 3).toString()));
        b.setProtein(Double.parseDouble(model.getValueAt(table_besin.getSelectedRow(), 4).toString()));
        b.setYag(Double.parseDouble(model.getValueAt(table_besin.getSelectedRow(), 5).toString()));
        b.setBesinkategori(this.getSystemFacede().getBesinkategoriSystem().getBkdao().find(model.getValueAt(table_besin.getSelectedRow(), 6).toString()));

        this.getSystemFacede().getMusteriSystem().getMdao().yemekEkle(b, this.getSystemFacede().getMusteriSystem().getM());

        this.tuketilenbesinGoster();
    }//GEN-LAST:event_btn_besin_ekleActionPerformed

    private void txt_yemekAraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_yemekAraKeyPressed

        this.yemekGoster(txt_yemekAra.getText());

    }//GEN-LAST:event_txt_yemekAraKeyPressed

    private void txt_yemekAraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_yemekAraKeyReleased
        this.yemekGoster(txt_yemekAra.getText());
    }//GEN-LAST:event_txt_yemekAraKeyReleased

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        this.setVisible(false);
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
    }//GEN-LAST:event_btn_cikisActionPerformed

    public void musteri_goster(Musteri m) {
        this.model = (DefaultTableModel) table_musteri.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        Object[] row = new Object[11];
        row[0] = m.getAd_soyad();
        row[1] = m.getCinsiyet();
        row[2] = m.getYas();
        row[3] = m.getBoy();
        row[4] = m.getKilo();
        row[5] = m.getYag_orani();
        row[6] = m.getHedef();
        row[7] = m.getGunluk_kalori_ihtiyaci();
        row[8] = m.getGunluk_karbonhidrat_ihtiyaci();
        row[9] = m.getGunluk_protein_ihtiyaci();
        row[10] = m.getGunluk_yag_ihtiyaci();
        model.addRow(row);

    }

    public void yemekGoster(String deger) {
        List<Besin> bl = this.getSystemFacede().getBesinSystem().getBdao().ara(deger);
        this.model = (DefaultTableModel) table_besin.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        Object[] row = new Object[7];
        for (int i = 0; i < bl.size(); i++) {
            row[0] = bl.get(i).getBesin_id();
            row[1] = bl.get(i).getIsim();
            row[2] = bl.get(i).getKalori();
            row[3] = bl.get(i).getKarbonhidrat();
            row[4] = bl.get(i).getProtein();
            row[5] = bl.get(i).getYag();
            row[6] = bl.get(i).getBesinkategori().getBesinkategori_isim();
            model.addRow(row);
        }

    }

    public void tuketilenbesinGoster() {

        List<Besin> bl = this.getSystemFacede().getMusteriSystem().getM().getTuketilenBesinler();
        //  List<Besin> bl = this.musteri.getTuketilenBesinler();
        this.model = (DefaultTableModel) table_tuketilenbesinler.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        Object[] row = new Object[1];
        for (int i = 0; i < bl.size(); i++) {
            row[0] = bl.get(i).getIsim();
            model.addRow(row);
        }
        List<Double> tuketilenler = this.getSystemFacede().getMusteriSystem().getMdao().tuketilenMakroHesapla(this.getSystemFacede().getMusteriSystem().getM());
        this.getTxt_tuketilenKalori().setText(tuketilenler.get(0).toString());
        this.getTxt_tuketilenKarbonhidrat().setText(tuketilenler.get(1).toString());
        this.getTxt_tuketilenProtein().setText(tuketilenler.get(2).toString());
        this.getTxt_tuketilenYag().setText(tuketilenler.get(3).toString());

        double kalanKalori = this.getSystemFacede().getMusteriSystem().getM().getGunluk_kalori_ihtiyaci() - tuketilenler.get(0);
        double kalanKarbonhidrat = this.getSystemFacede().getMusteriSystem().getM().getGunluk_karbonhidrat_ihtiyaci() - tuketilenler.get(1);
        double kalanProtein = this.getSystemFacede().getMusteriSystem().getM().getGunluk_protein_ihtiyaci() - tuketilenler.get(2);
        double kalanYag = this.getSystemFacede().getMusteriSystem().getM().getGunluk_yag_ihtiyaci() - tuketilenler.get(3);

        this.kalanHesapla(kalanKalori, kalanKarbonhidrat, kalanProtein, kalanYag);

    }

    public void kalanHesapla(double kalanKalori, double kalanKarbonhidrat, double kalanProtein, double kalanYag) {
        if (kalanKalori <= 0.0) {
            if (this.i != 0) {
                JOptionPane.showMessageDialog(this, "Tebrikler! Günlük Kalori hedefinize ulaştınız! ");
            }

            this.getTxt_kalanKalori().setText("0.0");
        } else {
            this.getTxt_kalanKalori().setText(String.valueOf(kalanKalori));
        }
        if (kalanKarbonhidrat <= 0.0) {
            if (this.i != 0) {
                JOptionPane.showMessageDialog(this, "Tebrikler! Günlük Karbonhidrat hedefinize ulaştınız! ");
            }

            this.getTxt_kalanKarbonhidrat().setText("0.0");
        } else {
            this.getTxt_kalanKarbonhidrat().setText(String.valueOf(kalanKarbonhidrat));
        }
        if (kalanProtein <= 0.0) {
            if (this.i != 0) {
                JOptionPane.showMessageDialog(this, "Tebrikler! Günlük Protein hedefinize ulaştınız! ");
            }

            this.getTxt_kalanProtein().setText("0.0");
        } else {
            this.getTxt_kalanProtein().setText(String.valueOf(kalanProtein));
        }
        if (kalanYag <= 0.0) {
            if (this.i != 0) {
                JOptionPane.showMessageDialog(this, "Tebrikler! Günlük Yag hedefinize ulaştınız! ");
            }

            this.getTxt_kalanYag().setText("0.0");
        } else {
            this.getTxt_kalanYag().setText(String.valueOf(kalanYag));
        }
        this.i++;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteriForm().setVisible(true);
            }
        });
    }

    public SystemFacede getSystemFacede() {
        if (this.systemFacede == null) {
            this.systemFacede = new SystemFacede();
        }
        return systemFacede;
    }

    public void setSystemFacede(SystemFacede systemFacede) {
        this.systemFacede = systemFacede;
    }

    public DefaultTableModel getModel() {
        return model;
    }

    public void setModel(DefaultTableModel model) {
        this.model = model;
    }

    public musteriBilgiGuncelle getBform() {
        if (this.bform == null) {
            this.bform = new musteriBilgiGuncelle();
        }
        return bform;
    }

    public void setBform(musteriBilgiGuncelle bform) {
        this.bform = bform;
    }

    public JTextField getTxt_kalanKalori() {
        return txt_kalanKalori;
    }

    public void setTxt_kalanKalori(JTextField txt_kalanKalori) {
        this.txt_kalanKalori = txt_kalanKalori;
    }

    public JTextField getTxt_kalanKarbonhidrat() {
        return txt_kalanKarbonhidrat;
    }

    public void setTxt_kalanKarbonhidrat(JTextField txt_kalanKarbonhidrat) {
        this.txt_kalanKarbonhidrat = txt_kalanKarbonhidrat;
    }

    public JTextField getTxt_kalanProtein() {
        return txt_kalanProtein;
    }

    public void setTxt_kalanProtein(JTextField txt_kalanProtein) {
        this.txt_kalanProtein = txt_kalanProtein;
    }

    public JTextField getTxt_kalanYag() {
        return txt_kalanYag;
    }

    public void setTxt_kalanYag(JTextField txt_kalanYag) {
        this.txt_kalanYag = txt_kalanYag;
    }

    public JTextField getTxt_tuketilenKalori() {
        return txt_tuketilenKalori;
    }

    public void setTxt_tuketilenKalori(JTextField txt_tuketilenKalori) {
        this.txt_tuketilenKalori = txt_tuketilenKalori;
    }

    public JTextField getTxt_tuketilenKarbonhidrat() {
        return txt_tuketilenKarbonhidrat;
    }

    public void setTxt_tuketilenKarbonhidrat(JTextField txt_tuketilenKarbonhidrat) {
        this.txt_tuketilenKarbonhidrat = txt_tuketilenKarbonhidrat;
    }

    public JTextField getTxt_tuketilenProtein() {
        return txt_tuketilenProtein;
    }

    public void setTxt_tuketilenProtein(JTextField txt_tuketilenProtein) {
        this.txt_tuketilenProtein = txt_tuketilenProtein;
    }

    public JTextField getTxt_tuketilenYag() {
        return txt_tuketilenYag;
    }

    public void setTxt_tuketilenYag(JTextField txt_tuketilenYag) {
        this.txt_tuketilenYag = txt_tuketilenYag;
    }

    public List<NoticeObservable> getNlist() {
        return nlist;
    }

    public void setNlist(List<NoticeObservable> nlist) {
        this.nlist = nlist;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_besin_ekle;
    private javax.swing.JButton btn_bilgileri_guncelle;
    private javax.swing.JButton btn_cikis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_kalori;
    private javax.swing.JLabel label_kalori1;
    private javax.swing.JTable table_besin;
    private javax.swing.JTable table_musteri;
    private javax.swing.JTable table_tuketilenbesinler;
    private javax.swing.JTextField txt_kalanKalori;
    private javax.swing.JTextField txt_kalanKarbonhidrat;
    private javax.swing.JTextField txt_kalanProtein;
    private javax.swing.JTextField txt_kalanYag;
    private javax.swing.JTextField txt_tuketilenKalori;
    private javax.swing.JTextField txt_tuketilenKarbonhidrat;
    private javax.swing.JTextField txt_tuketilenProtein;
    private javax.swing.JTextField txt_tuketilenYag;
    private javax.swing.JTextField txt_yemekAra;
    // End of variables declaration//GEN-END:variables
}
