/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import SystemsController.MusteriSystem;
import SystemsController.SystemFacede;
import entity.Musteri;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public final class musteriBilgiGuncelle extends javax.swing.JFrame {

    private SystemFacede systemFacede;

    private musteriForm mform;

    public musteriBilgiGuncelle() {
        initComponents();
    }

   
     
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_boy = new javax.swing.JTextField();
        radiobutton_erkek = new javax.swing.JRadioButton();
        radiobutton_kadın = new javax.swing.JRadioButton();
        radiobutton_kiloalmak = new javax.swing.JRadioButton();
        radiobutton_yagyakmak = new javax.swing.JRadioButton();
        btn_guncelle = new javax.swing.JButton();
        btn_geri = new javax.swing.JButton();
        txt_telefon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_loginName = new javax.swing.JTextField();
        txt_adSoyad = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_yas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_kilo = new javax.swing.JTextField();
        txt_yag = new javax.swing.JTextField();
        checkBox_bildirim = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radiobutton_erkek.setText("Erkek");
        radiobutton_erkek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobutton_erkekActionPerformed(evt);
            }
        });

        radiobutton_kadın.setText("Kadın");

        radiobutton_kiloalmak.setText("Kilo alma");

        radiobutton_yagyakmak.setText("Yağ yakma");

        btn_guncelle.setText("Güncelle");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_geri.setText("Geri");
        btn_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriActionPerformed(evt);
            }
        });

        txt_telefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonActionPerformed(evt);
            }
        });

        jLabel9.setText("KULLANICI ADI :");

        jLabel14.setText("*YAG ORANI(%) :");

        jLabel15.setText("*HEDEF :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("KİŞİSEL BİLGİLER :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("FİZİKSEL BİLGİLER :");

        jLabel10.setText("***Vücut analizinizin yapılması ve hedefinize göre kalori-makro değerlerinin hesaplanabilmesi için bu bilgilerin eksiksiz girilmesi gerekmektedir.");

        txt_loginName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginNameActionPerformed(evt);
            }
        });

        txt_email.setText("ornek@gmail.com");

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        jLabel1.setText("AD-SOYAD :");

        jLabel2.setText("TELEFON :");

        jLabel3.setText("ŞİFRE :");

        jLabel6.setText("EMAİL :");

        jLabel7.setText("*BOY(CM)  :");

        jLabel8.setText("*KİLO(KG) :");

        jLabel12.setText("*YAŞ :");

        jLabel13.setText("*CİNSİYET :");

        txt_yag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_yagActionPerformed(evt);
            }
        });

        checkBox_bildirim.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        checkBox_bildirim.setText("Kampanyalardan ve Uygulama içi Genel Bildirimlerden Haberdar Olmak İstiyorum.");
        checkBox_bildirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_bildirimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_loginName, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                                    .addComponent(txt_adSoyad))
                                                .addGap(159, 159, 159)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(208, 208, 208))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_geri, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBox_bildirim)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel12))
                                                .addGap(52, 52, 52)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_boy, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_yas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_kilo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(234, 234, 234)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel14)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txt_yag, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel15)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(radiobutton_kiloalmak))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(jLabel13)
                                                            .addGap(28, 28, 28)
                                                            .addComponent(radiobutton_erkek))))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radiobutton_kadın)
                                            .addComponent(radiobutton_yagyakmak))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_adSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_loginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(txt_yas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_yag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_boy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radiobutton_erkek)
                        .addComponent(radiobutton_kadın)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(txt_kilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radiobutton_kiloalmak)
                    .addComponent(radiobutton_yagyakmak))
                .addGap(22, 22, 22)
                .addComponent(checkBox_bildirim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_geri, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radiobutton_erkekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobutton_erkekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobutton_erkekActionPerformed

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed

        if (txt_yas.getText().equalsIgnoreCase("") || txt_boy.getText().equalsIgnoreCase("") || txt_kilo.getText().equalsIgnoreCase("") || txt_yag.getText().equalsIgnoreCase("") || (!radiobutton_erkek.isSelected() && !radiobutton_kadın.isSelected()) || (!radiobutton_kiloalmak.isSelected() && !radiobutton_yagyakmak.isSelected())) {

            JOptionPane.showMessageDialog(this, " (*) ile işaretli alanlar boş bırakılamaz!");

        } else if (radiobutton_erkek.isSelected() && radiobutton_kadın.isSelected()) {
            JOptionPane.showMessageDialog(this, " İki cinsiyet seçimi yapılamaz!");
        } else if (radiobutton_kiloalmak.isSelected() && radiobutton_yagyakmak.isSelected()) {
            JOptionPane.showMessageDialog(this, " İki hedef aynı anda seçilemez!");
        } else {
            this.getSystemFacede().getMusteriSystem().getM().setAd_soyad(txt_adSoyad.getText());
            this.getSystemFacede().getMusteriSystem().getM().setLogin_name(txt_loginName.getText());
            this.getSystemFacede().getMusteriSystem().getM().setPassword(txt_password.getText());
            this.getSystemFacede().getMusteriSystem().getM().setTelefon(txt_telefon.getText());
            this.getSystemFacede().getMusteriSystem().getM().setEmail(txt_email.getText());
            this.getSystemFacede().getMusteriSystem().getM().setYas(Integer.parseInt(txt_yas.getText()));
            this.getSystemFacede().getMusteriSystem().getM().setBoy(Integer.parseInt(txt_boy.getText()));
            this.getSystemFacede().getMusteriSystem().getM().setKilo(Double.parseDouble(txt_kilo.getText()));
            this.getSystemFacede().getMusteriSystem().getM().setYag_orani(Double.parseDouble(txt_yag.getText()));
            if (radiobutton_erkek.isSelected()) {
                this.getSystemFacede().getMusteriSystem().getM().setCinsiyet(radiobutton_erkek.getText());
            } else {
                this.getSystemFacede().getMusteriSystem().getM().setCinsiyet(radiobutton_kadın.getText());
            }
            if (radiobutton_kiloalmak.isSelected()) {
                this.getSystemFacede().getMusteriSystem().getM().setHedef(radiobutton_kiloalmak.getText());
            } else {
                this.getSystemFacede().getMusteriSystem().getM().setHedef(radiobutton_yagyakmak.getText());
            }
            if (checkBox_bildirim.isSelected()) {
                this.getSystemFacede().getMusteriSystem().getM().setBildirim(true);
            } else {
                this.getSystemFacede().getMusteriSystem().getM().setBildirim(false);
            }
            this.getSystemFacede().getMusteriSystem().update();

            this.mform.musteri_goster(this.systemFacede.getMusteriSystem().getM());
            this.mform.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_geriActionPerformed

    private void txt_telefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonActionPerformed

    private void txt_loginNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loginNameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_yagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_yagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_yagActionPerformed

    private void checkBox_bildirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_bildirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBox_bildirimActionPerformed

    public void bilgileriGetir(Musteri m) {
        txt_adSoyad.setText(m.getAd_soyad());
        txt_loginName.setText(m.getLogin_name());
        txt_password.setText(m.getPassword());
        txt_email.setText(m.getEmail());
        txt_telefon.setText(m.getTelefon());
        txt_yas.setText(String.valueOf(m.getYas()));
        txt_boy.setText(String.valueOf(m.getBoy()));
        txt_kilo.setText(String.valueOf(m.getKilo()));
        txt_yag.setText(String.valueOf(m.getYag_orani()));
        if (m.getCinsiyet().equalsIgnoreCase(radiobutton_erkek.getText())) {
            radiobutton_erkek.doClick();
        } else {
            radiobutton_kadın.doClick();
        }
        if (m.getHedef().equalsIgnoreCase(radiobutton_kiloalmak.getText())) {
            radiobutton_kiloalmak.doClick();
        } else {
            radiobutton_yagyakmak.doClick();
        }
        if (m.isBildirim()) {
            checkBox_bildirim.doClick();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteriBilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteriBilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteriBilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteriBilgiGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteriBilgiGuncelle().setVisible(true);
            }
        });
    }

    public SystemFacede getSystemFacede() {
        if (this.systemFacede == null) {
            this.systemFacede = new SystemFacede();
        }
        return systemFacede;
    }

    public musteriForm getMform() {
        if (this.mform == null) {
            this.mform = new musteriForm();
        }
        return mform;
    }

    public void setMfrom(musteriForm mform) {
        this.mform = mform;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geri;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JCheckBox checkBox_bildirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radiobutton_erkek;
    private javax.swing.JRadioButton radiobutton_kadın;
    private javax.swing.JRadioButton radiobutton_kiloalmak;
    private javax.swing.JRadioButton radiobutton_yagyakmak;
    private javax.swing.JTextField txt_adSoyad;
    private javax.swing.JTextField txt_boy;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_kilo;
    private javax.swing.JTextField txt_loginName;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_telefon;
    private javax.swing.JTextField txt_yag;
    private javax.swing.JTextField txt_yas;
    // End of variables declaration//GEN-END:variables
}
